[debug] [2024-07-17T12:15:32.936Z] ----------------------------------------------------------------------
[debug] [2024-07-17T12:15:32.938Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --only hosting
[debug] [2024-07-17T12:15:32.938Z] CLI Version:   12.6.1
[debug] [2024-07-17T12:15:32.938Z] Platform:      darwin
[debug] [2024-07-17T12:15:32.939Z] Node Version:  v18.18.0
[debug] [2024-07-17T12:15:32.939Z] Time:          Wed Jul 17 2024 20:15:32 GMT+0800 (Philippine Standard Time)
[debug] [2024-07-17T12:15:32.939Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-07-17T12:15:33.007Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-07-17T12:15:33.007Z] > authorizing via signed-in user (jovanneolalo@gmail.com)
[debug] [2024-07-17T12:15:33.008Z] [iam] checking project jovannecuynoolalo for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-07-17T12:15:33.009Z] > refreshing access token with scopes: []
[debug] [2024-07-17T12:15:33.011Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-07-17T12:15:33.011Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-17T12:16:54.289Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------302653166856839876046285","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4017:803::200a:443
[debug] [2024-07-17T12:16:54.290Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-07-17T12:16:54.290Z] > refreshing access token with scopes: []
[debug] [2024-07-17T12:16:54.291Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-07-17T12:16:54.291Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-17T12:16:59.886Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2024-07-17T12:16:59.886Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-17T12:16:59.939Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/jovannecuynoolalo [none]
[debug] [2024-07-17T12:17:29.942Z] *** [apiv2] error from fetch(https://firebase.googleapis.com/v1beta1/projects/jovannecuynoolalo, {"headers":{},"method":"GET","signal":{}}): AbortError: The user aborted a request.
[debug] [2024-07-17T12:17:29.942Z] Timeout reached making request to https://firebase.googleapis.com/v1beta1/projects/jovannecuynoolalo (original: The user aborted a request.)
[debug] [2024-07-17T12:17:34.948Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-07-17T12:23:18.480Z] ----------------------------------------------------------------------
[debug] [2024-07-17T12:23:18.482Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login:ci
[debug] [2024-07-17T12:23:18.482Z] CLI Version:   12.6.1
[debug] [2024-07-17T12:23:18.482Z] Platform:      darwin
[debug] [2024-07-17T12:23:18.483Z] Node Version:  v18.18.0
[debug] [2024-07-17T12:23:18.483Z] Time:          Wed Jul 17 2024 20:23:18 GMT+0800 (Philippine Standard Time)
[debug] [2024-07-17T12:23:18.483Z] ----------------------------------------------------------------------
[debug] 
[warn] âš   Authenticating with a `login:ci` token is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=481694675&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-07-17T12:23:55.510Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-07-17T12:23:55.511Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-07-17T12:25:16.848Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------490292576500984752479670","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2404:6800:4008:c04::54:443
[debug] [2024-07-17T12:25:16.848Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:239:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-07-17T12:25:16.853Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-07-17T12:25:16.854Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"f23e763d-db4c-4381-a889-d1d407836df5"}
[debug] [2024-07-17T12:25:24.668Z] ----------------------------------------------------------------------
[debug] [2024-07-17T12:25:24.670Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login
[debug] [2024-07-17T12:25:24.670Z] CLI Version:   12.6.1
[debug] [2024-07-17T12:25:24.670Z] Platform:      darwin
[debug] [2024-07-17T12:25:24.671Z] Node Version:  v18.18.0
[debug] [2024-07-17T12:25:24.671Z] Time:          Wed Jul 17 2024 20:25:24 GMT+0800 (Philippine Standard Time)
[debug] [2024-07-17T12:25:24.672Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as jovanneolalo@gmail.com
[debug] [2024-07-17T12:25:34.788Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-07-17T12:25:41.569Z] ----------------------------------------------------------------------
[debug] [2024-07-17T12:25:41.570Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login
[debug] [2024-07-17T12:25:41.571Z] CLI Version:   12.6.1
[debug] [2024-07-17T12:25:41.571Z] Platform:      darwin
[debug] [2024-07-17T12:25:41.571Z] Node Version:  v18.18.0
[debug] [2024-07-17T12:25:41.572Z] Time:          Wed Jul 17 2024 20:25:41 GMT+0800 (Philippine Standard Time)
[debug] [2024-07-17T12:25:41.572Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as jovanneolalo@gmail.com
[debug] [2024-07-17T12:25:51.679Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
